{{- if .Values.provisioner.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orochi-cloud.provisioner.fullname" . }}-secret
  namespace: {{ include "orochi-cloud.namespace" . }}
  labels:
    {{- include "orochi-cloud.provisioner.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if eq .Values.provisioner.cloudProvider.type "aws" }}
  {{- if .Values.provisioner.cloudProvider.aws.accessKeyId }}
  AWS_ACCESS_KEY_ID: {{ .Values.provisioner.cloudProvider.aws.accessKeyId | b64enc | quote }}
  {{- end }}
  {{- if .Values.provisioner.cloudProvider.aws.secretAccessKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.provisioner.cloudProvider.aws.secretAccessKey | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if eq .Values.provisioner.cloudProvider.type "gcp" }}
  {{- if .Values.provisioner.cloudProvider.gcp.credentials }}
  GOOGLE_APPLICATION_CREDENTIALS_JSON: {{ .Values.provisioner.cloudProvider.gcp.credentials | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if eq .Values.provisioner.cloudProvider.type "azure" }}
  {{- if .Values.provisioner.cloudProvider.azure.subscriptionId }}
  AZURE_SUBSCRIPTION_ID: {{ .Values.provisioner.cloudProvider.azure.subscriptionId | b64enc | quote }}
  {{- end }}
  {{- if .Values.provisioner.cloudProvider.azure.tenantId }}
  AZURE_TENANT_ID: {{ .Values.provisioner.cloudProvider.azure.tenantId | b64enc | quote }}
  {{- end }}
  {{- if .Values.provisioner.cloudProvider.azure.clientId }}
  AZURE_CLIENT_ID: {{ .Values.provisioner.cloudProvider.azure.clientId | b64enc | quote }}
  {{- end }}
  {{- if .Values.provisioner.cloudProvider.azure.clientSecret }}
  AZURE_CLIENT_SECRET: {{ .Values.provisioner.cloudProvider.azure.clientSecret | b64enc | quote }}
  {{- end }}
  {{- end }}
  # Placeholder for local development
  PROVISIONER_TOKEN: {{ "provisioner-internal-token" | b64enc | quote }}
{{- end }}
