{{- if .Values.provisioner.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "orochi-cloud.provisioner.fullname" . }}
  namespace: {{ include "orochi-cloud.namespace" . }}
  labels:
    {{- include "orochi-cloud.provisioner.labels" . | nindent 4 }}
  {{- with .Values.provisioner.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.provisioner.service.type }}
  ports:
    - port: {{ .Values.provisioner.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "orochi-cloud.provisioner.selectorLabels" . | nindent 4 }}
{{- end }}
