apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dashboard-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - console-staging.orochi-cloud.io
      secretName: dashboard-staging-tls
  rules:
    - host: console-staging.orochi-cloud.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: staging-dashboard
                port:
                  name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api-staging.orochi-cloud.io
      secretName: api-staging-tls
  rules:
    - host: api-staging.orochi-cloud.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: staging-control-plane
                port:
                  name: http
