{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: {{ include "pgdog-router.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "pgdog-router.fullname" . }}
  labels:
    {{- include "pgdog-router.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- else if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- else }}
  minAvailable: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "pgdog-router.selectorLabels" . | nindent 6 }}
{{- end }}
