{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgdog-router.fullname" . }}
  labels:
    {{- include "pgdog-router.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{- range $user, $password := .Values.secrets.credentials }}
  {{ $user }}-password: {{ $password | b64enc | quote }}
  {{- end }}
{{- end }}
---
{{- if and .Values.pgdog.tls.enabled (not .Values.pgdog.tls.existingSecret) .Values.pgdog.tls.certificate }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgdog-router.tlsSecretName" . }}
  labels:
    {{- include "pgdog-router.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.pgdog.tls.certificate | b64enc | quote }}
  tls.key: {{ .Values.pgdog.tls.privateKey | b64enc | quote }}
  {{- if .Values.pgdog.tls.caCertificate }}
  ca.crt: {{ .Values.pgdog.tls.caCertificate | b64enc | quote }}
  {{- end }}
{{- end }}
---
{{- if and .Values.jwtProxy.enabled (not .Values.jwtProxy.existingSecret) .Values.jwtProxy.jwtSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgdog-router.jwtSecretName" . }}
  labels:
    {{- include "pgdog-router.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.jwtProxy.existingSecretKey }}: {{ .Values.jwtProxy.jwtSecret | b64enc | quote }}
{{- end }}
